### ISSUE TITLE
error on remove_numts_no_split_gap.sh

### ISSUE THREAD

**Issue by ASC689561** [timmykuo/mitopipeline#1]
hi timmy, When I ran I saw an error in remove_numts_no_split_gap.sh  at line 221, 245.
if (( $LENGTH < 70 ))
i fix that by:
if [[ $LENGTH < 70 ]]
Is that right?

**Comment by timmykuo** [comment]
Hi, thanks for pointing that out. It seems that some POSIX shells do not support (( )) for arithmetic comparing, which may be why you're running into that error. I believe the correct way to do this comparison is actually [ $LENGTH  -lt 70 ] instead. I'll update that now – thanks again!
